spring:
  application:
    name: application-service
  config:
    import: "configserver:http://localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
